version: "3.5"

services:
  db:
    # networks:
    #   - network
    # platform: linux/x86_64
    image: mysql:8.0
    container_name: appsDB
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    env_file:
      - docker.env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    # networks:
    #   - network
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

  # app:
  #   platform: linux/amd64
  #   networks:
  #     - network
  #   depends_on:
  #     - db
  #   build:
  #     context: ./project
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   container_name: project
  #   restart: always
  #   ports:
  #     - "3000:3000" # Adjust the port as needed
  #   volumes:
  #     - ./project:/project
  #   command:
  #     - bash
  #     - -c
  #     - |
  #       /project/wait-for-it.sh appsDB:3306 -t 10
  #       npm run start
# networks:
#   network:
#     driver: bridge
